repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.9 #Get the latest from: https://github.com/gruntwork-io/pre-commit/releases
    hooks:
      - id: tflint
      - id: helmlint
      - id: shellcheck
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0  # Use the ref you want to point at
    hooks:
      - id: check-json
      - id: check-yaml
      - id: mixed-line-ending
      - id: no-commit-to-branch
